sudo: true
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libgmp-dev
install:
  - git clone https://github.com/herumi/mcl.git $TRAVIS_BUILD_DIR/../mcl
#  - git clone -b dev https://github.com/herumi/mcl.git $TRAVIS_BUILD_DIR/../mcl
script:
  - make -j3
  - make test_ci
  - make test_go
  - env LD_LIBRARY_PATH=../mcl/lib bin/bls_c384_test.exe
  - make clean && make -C ../mcl clean
  - make -C ../mcl lib/libmcl.a MCL_USE_GMP=0
  - make -j3 MCL_USE_GMP=0
  - make test_ci CFLAGS_USER="-DDISABLE_THREAD_TEST" MCL_USE_GMP=0
  - make clean
  - make test_ci CFLAGS_USER="-DDISABLE_THREAD_TEST" MCL_USE_GMP=0 BLS_ETH=1
