sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt install -y libgmp-dev
script:
  - git clone --depth 1 https://github.com/herumi/mcl.git
  - git clone --depth 1 https://github.com/herumi/bls.git
  - cd bls
  - make
  - make test DISABLE_THREAD_TEST=1
  - make test_go
  - bin/bls_c384_test.exe
