name: test
on: [push]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: lscpu
    - run: git clone --depth 1 https://github.com/herumi/mcl
    - run: make -C ./mcl lib/libmcl.a -j4
    - run: make test_ci MCL_DIR=$(pwd)/mcl -j4 || dmesg | tail
    - run: make clean MCL_DIR=$(pwd)/mcl
    - run: make test_go MCL_DIR=$(pwd)/mcl -j4
    - run: make clean MCL_DIR=$(pwd)/mcl
    - run: make test_ci MCL_DIR=$(pwd)/mcl BLS_ETH=1 -j4
    - run: make clean MCL_DIR=$(pwd)/mcl
    - run: make test_ci MCL_DIR=$(pwd)/mcl BLS_ETH=1 CXX=clang++ -j4
